
import type { JobListing, Industry, JobType, ExperienceLevel, Category, Employer, Testimonial } from '@/types';

export const mockJobs: JobListing[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'Tech Solutions PLC',
    location: 'Addis Ababa',
    snippet: 'Seeking an experienced Frontend Developer to build responsive and performant web applications using React and TypeScript.',
    fullDescription: 'Tech Solutions PLC is a leading innovator in the Ethiopian tech scene. We are looking for a highly skilled Senior Frontend Developer to join our dynamic team. Responsibilities include developing user-facing features, ensuring the technical feasibility of UI/UX designs, and optimizing applications for maximum speed and scalability. You will collaborate with other team members and stakeholders. Requirements: 5+ years of experience with React, TypeScript, HTML, CSS, and modern JavaScript frameworks. Strong understanding of responsive design principles and RESTful APIs.',
    jobUrl: 'https://example.com/job/1',
    industry: 'Technology',
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    postedDate: '2024-07-20',
    logoUrl: 'https://placehold.co/100x100.png',
    isFeatured: true,
    salaryRange: '$2000-$3000',
  },
  {
    id: '2',
    title: 'Digital Marketing Specialist',
    company: 'Connect Ethiopia',
    location: 'Addis Ababa',
    snippet: 'Join our marketing team to manage digital campaigns, SEO/SEM, and social media presence. Proven experience required.',
    fullDescription: 'Connect Ethiopia is expanding its marketing efforts and seeks a Digital Marketing Specialist. You will be responsible for planning and executing all digital marketing, including SEO/SEM, marketing database, email, social media, and display advertising campaigns. Measuring and reporting on the performance of all digital marketing campaigns is key. Requirements: 3+ years of digital marketing experience. Demonstrable experience leading and managing SEO/SEM, marketing database, email, social media and/or display advertising campaigns.',
    jobUrl: 'https://example.com/job/2',
    industry: 'Marketing',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-18',
    logoUrl: 'https://placehold.co/100x100.png',
    salaryRange: '$1500-$2500',
  },
  {
    id: '3',
    title: 'Accountant',
    company: 'Finance Hub',
    location: 'Hawassa',
    snippet: 'Responsible for managing financial records, preparing reports, and ensuring compliance. CPA or equivalent preferred.',
    fullDescription: 'Finance Hub in Hawassa is looking for a detail-oriented Accountant. The role involves managing all accounting transactions, preparing budget forecasts, publishing financial statements in time, and handling monthly, quarterly, and annual closings. You will also ensure timely bank payments and reconcile accounts payable and receivable. Requirements: BSc in Accounting, Finance or relevant degree. Additional certification (CPA or CMA) is a plus. Proven work experience as an Accountant.',
    jobUrl: 'https://example.com/job/3',
    industry: 'Finance',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-22',
    isFeatured: true,
    salaryRange: '$1000-$1800',
  },
  {
    id: '4',
    title: 'Registered Nurse',
    company: 'City General Hospital',
    location: 'Dire Dawa',
    snippet: 'Provide patient care in a fast-paced hospital environment. Must be a licensed RN with at least 2 years of experience.',
    fullDescription: 'City General Hospital in Dire Dawa is hiring a compassionate and skilled Registered Nurse. You will be responsible for assessing patient conditions, administering medications, and providing emotional support to patients and their families. This role requires excellent communication skills and the ability to work in a high-pressure environment. Requirements: Valid RN license in Ethiopia. Minimum 2 years of nursing experience in a hospital setting. BLS/ACLS certification preferred.',
    jobUrl: 'https://example.com/job/4',
    industry: 'Healthcare',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-15',
    logoUrl: 'https://placehold.co/100x100.png',
    salaryRange: '$800-$1500',
  },
  {
    id: '5',
    title: 'Software Engineering Intern',
    company: 'Innovate Tech',
    location: 'Addis Ababa',
    snippet: 'Exciting internship opportunity for aspiring software engineers to work on real-world projects. Basic programming knowledge needed.',
    fullDescription: 'Innovate Tech offers a dynamic Software Engineering Internship program. Interns will gain hands-on experience by contributing to ongoing projects, working alongside experienced developers, and learning about the full software development lifecycle. This is a great opportunity to develop your skills in a supportive environment. Requirements: Currently pursuing or recently completed a degree in Computer Science or a related field. Basic understanding of programming concepts (e.g., Python, Java, JavaScript). Eagerness to learn and contribute.',
    jobUrl: 'https://example.com/job/5',
    industry: 'Technology',
    jobType: 'Internship',
    experienceLevel: 'Entry',
    postedDate: '2024-07-25',
    isFeatured: true,
    salaryRange: 'Competitive Stipend',
  },
  {
    id: '6',
    title: 'Civil Engineer',
    company: 'BuildRight Construction',
    location: 'Bahir Dar',
    snippet: 'Seeking a qualified Civil Engineer for infrastructure projects. Must have a degree in Civil Engineering and relevant site experience.',
    fullDescription: 'BuildRight Construction is a leading firm in Bahir Dar, specializing in large-scale infrastructure projects. We need an experienced Civil Engineer to manage project planning, execution, and oversight. Responsibilities include site investigations, technical designs, and ensuring projects meet safety and quality standards. Requirements: Bachelor’s degree in Civil Engineering. 5+ years of experience in construction project management. Proficiency in AutoCAD and project management software.',
    jobUrl: 'https://example.com/job/6',
    industry: 'Engineering',
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    postedDate: '2024-07-10',
    salaryRange: '$2500-$3500',
  },
   {
    id: '7',
    title: 'UX Designer',
    company: 'Creative Labs',
    location: 'Addis Ababa',
    snippet: 'We are looking for a talented UX Designer to create intuitive and engaging user experiences for our web and mobile products.',
    fullDescription: 'Creative Labs is at the forefront of user-centered design in Ethiopia. As a UX Designer, you will conduct user research, create wireframes, prototypes, and user flows, and collaborate with product managers and engineers to deliver outstanding digital products. Requirements: 3+ years of UX design experience. A strong portfolio showcasing your design process and solutions. Proficiency in design tools like Figma, Sketch, or Adobe XD.',
    jobUrl: 'https://example.com/job/7',
    industry: 'Design',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-28',
    logoUrl: 'https://placehold.co/100x100.png',
    isFeatured: true,
    salaryRange: '$1800-$2800',
  },
  {
    id: '8',
    title: 'Sales Manager',
    company: 'EthioGoods Inc.',
    location: 'Adama',
    snippet: 'Dynamic Sales Manager needed to lead our sales team and expand market reach. Proven track record in sales leadership.',
    fullDescription: 'EthioGoods Inc., based in Adama, is seeking a results-driven Sales Manager to lead our growing sales department. You will be responsible for developing sales strategies, managing the sales team, building client relationships, and achieving sales targets. Requirements: 5+ years of sales experience, with at least 2 years in a managerial role. Excellent leadership and communication skills. Proven ability to drive sales growth.',
    jobUrl: 'https://example.com/job/8',
    industry: 'Sales',
    jobType: 'Full-time',
    experienceLevel: 'Manager',
    postedDate: '2024-07-26',
    salaryRange: '$2200-$3200 + Commission',
  },
  {
    id: '9',
    title: 'Part-time English Tutor',
    company: 'LearnWell Academy',
    location: 'Addis Ababa',
    snippet: 'Part-time opportunity for experienced English tutors to teach students of various levels. Flexible hours.',
    fullDescription: 'LearnWell Academy is looking for dedicated Part-time English Tutors in Addis Ababa. Tutors will provide English language instruction to students of different age groups and proficiency levels. Responsibilities include lesson planning, delivering engaging lessons, and assessing student progress. Requirements: Excellent command of the English language. Previous teaching or tutoring experience. TEFL/TESOL certification is a plus. Flexible availability.',
    jobUrl: 'https://example.com/job/9',
    industry: 'Education',
    jobType: 'Part-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-23',
    salaryRange: 'Negotiable Hourly Rate',
  },
  {
    id: '10',
    title: 'Project Manager (Construction)',
    company: 'Mega Builders PLC',
    location: 'Mekelle',
    snippet: 'Experienced Project Manager to oversee large-scale construction projects from inception to completion. PMP certification is a plus.',
    fullDescription: 'Mega Builders PLC in Mekelle requires a seasoned Project Manager for its construction division. This role involves overseeing all aspects of construction projects, including planning, budgeting, scheduling, resource allocation, and risk management. You will ensure projects are completed on time, within budget, and to the highest quality standards. Requirements: Degree in Civil Engineering, Construction Management, or related field. 7+ years of experience in construction project management. PMP certification or equivalent is highly desirable.',
    jobUrl: 'https://example.com/job/10',
    industry: 'Engineering',
    jobType: 'Contract',
    experienceLevel: 'Lead',
    postedDate: '2024-07-19',
    logoUrl: 'https://placehold.co/100x100.png',
    salaryRange: '$3000-$4500',
  },
  {
    id: '11',
    title: 'Customer Service Representative',
    company: 'Ethio Telecom',
    location: 'Addis Ababa',
    snippet: 'Join Ethio Telecom as a Customer Service Rep. Excellent communication skills required.',
    fullDescription: 'Detailed description for Customer Service Rep at Ethio Telecom.',
    jobUrl: 'https://example.com/job/11',
    industry: 'Customer Service',
    jobType: 'Full-time',
    experienceLevel: 'Entry',
    postedDate: '2024-07-29',
    logoUrl: 'https://placehold.co/100x100.png',
    isFeatured: true,
    salaryRange: '$500-$800',
  },
  {
    id: '12',
    title: 'Delivery Driver',
    company: 'Zmall Delivery',
    location: 'Addis Ababa',
    snippet: 'Reliable delivery driver needed for city routes. Valid license and good driving record essential.',
    fullDescription: 'Detailed description for Delivery Driver at Zmall Delivery.',
    jobUrl: 'https://example.com/job/12',
    industry: 'Delivery',
    jobType: 'Part-time',
    experienceLevel: 'Entry',
    postedDate: '2024-07-30',
    logoUrl: 'https://placehold.co/100x100.png',
    salaryRange: 'Per Delivery + Tips',
  },
];

export const EthiopianMajorCities = [
  "Addis Ababa",
  "Adama",
  "Hawassa", // Updated from Awassa (Hawassa)
  "Bahir Dar",
  "Dire Dawa",
  "Gondar",
  "Mekelle",
  "Jimma",
  "Dessie",
  "Jijiga"
];

export const mockCategories: Category[] = [
  { id: 'cat1', name: 'Technology', jobCount: 3458, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'laptop code' },
  { id: 'cat2', name: 'Customer Service', jobCount: 2354, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'headset support' },
  { id: 'cat3', name: 'Delivery', jobCount: 1547, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'delivery van' },
  { id: 'cat4', name: 'Marketing', jobCount: 1785, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'marketing chart' },
  { id: 'cat5', name: 'HR', jobCount: 1754, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'team meeting' },
  { id: 'cat6', name: 'Healthcare', jobCount: 3457, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'doctor nurse' },
  { id: 'cat7', name: 'Accounting', jobCount: 6475, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'calculator ledger' },
  { id: 'cat8', name: 'Design', jobCount: 1200, imageUrl: 'https://placehold.co/400x300.png', aiHint: 'design tools' },
];

export const mockEmployers: Employer[] = [
  { id: 'emp1', name: 'Tanner Fultzke', logoUrl: 'https://placehold.co/100x100.png', aiHint: 'professional portrait' },
  { id: 'emp2', name: 'Shela Boyko', logoUrl: 'https://placehold.co/100x100.png', aiHint: 'professional portrait' },
  { id: 'emp3', name: 'Tod Uli', logoUrl: 'https://placehold.co/100x100.png', aiHint: 'professional portrait' },
  { id: 'emp4', name: 'Catherina Shoof', logoUrl: 'https://placehold.co/100x100.png', aiHint: 'professional portrait' },
  { id: 'emp5', name: 'Rejoin', logoUrl: 'https://placehold.co/150x50.png', aiHint: 'company logo' }, // Example of different size
];

export const mockTestimonials: Testimonial[] = [
  {
    id: 'test1',
    quote: 'EthioJobsConnect helped me find my dream job in just a week! The platform is user-friendly and has a vast number of opportunities.',
    authorName: 'Abebe Kebede',
    authorTitle: 'Software Engineer at Tech Solutions PLC',
    avatarUrl: 'https://placehold.co/80x80.png',
    aiHint: 'happy person'
  },
  {
    id: 'test2',
    quote: 'As a recruiter, EthioJobsConnect has been invaluable. We found highly qualified candidates quickly and efficiently.',
    authorName: 'Fatuma Ahmed',
    authorTitle: 'HR Manager at Connect Ethiopia',
    avatarUrl: 'https://placehold.co/80x80.png',
    aiHint: 'professional recruiter'
  },
];
