
import type { JobListing, Industry, JobType, ExperienceLevel } from '@/types';

export const mockJobs: JobListing[] = [
  {
    id: '1',
    title: 'Senior Frontend Developer',
    company: 'Tech Solutions PLC',
    location: 'Addis Ababa',
    snippet: 'Seeking an experienced Frontend Developer to build responsive and performant web applications using React and TypeScript.',
    jobUrl: 'https://example.com/job/1',
    industry: 'Technology',
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    postedDate: '2024-07-20',
    logoUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: '2',
    title: 'Digital Marketing Specialist',
    company: 'Connect Ethiopia',
    location: 'Addis Ababa',
    snippet: 'Join our marketing team to manage digital campaigns, SEO/SEM, and social media presence. Proven experience required.',
    jobUrl: 'https://example.com/job/2',
    industry: 'Marketing',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-18',
    logoUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: '3',
    title: 'Accountant',
    company: 'Finance Hub',
    location: 'Hawassa',
    snippet: 'Responsible for managing financial records, preparing reports, and ensuring compliance. CPA or equivalent preferred.',
    jobUrl: 'https://example.com/job/3',
    industry: 'Finance',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-22',
  },
  {
    id: '4',
    title: 'Registered Nurse',
    company: 'City General Hospital',
    location: 'Dire Dawa',
    snippet: 'Provide patient care in a fast-paced hospital environment. Must be a licensed RN with at least 2 years of experience.',
    jobUrl: 'https://example.com/job/4',
    industry: 'Healthcare',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-15',
    logoUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: '5',
    title: 'Software Engineering Intern',
    company: 'Innovate Tech',
    location: 'Addis Ababa',
    snippet: 'Exciting internship opportunity for aspiring software engineers to work on real-world projects. Basic programming knowledge needed.',
    jobUrl: 'https://example.com/job/5',
    industry: 'Technology',
    jobType: 'Internship',
    experienceLevel: 'Entry',
    postedDate: '2024-07-25',
  },
  {
    id: '6',
    title: 'Civil Engineer',
    company: 'BuildRight Construction',
    location: 'Bahir Dar',
    snippet: 'Seeking a qualified Civil Engineer for infrastructure projects. Must have a degree in Civil Engineering and relevant site experience.',
    jobUrl: 'https://example.com/job/6',
    industry: 'Engineering',
    jobType: 'Full-time',
    experienceLevel: 'Senior',
    postedDate: '2024-07-10',
  },
   {
    id: '7',
    title: 'UX Designer',
    company: 'Creative Labs',
    location: 'Addis Ababa',
    snippet: 'We are looking for a talented UX Designer to create intuitive and engaging user experiences for our web and mobile products.',
    jobUrl: 'https://example.com/job/7',
    industry: 'Technology',
    jobType: 'Full-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-28',
    logoUrl: 'https://placehold.co/100x100.png',
  },
  {
    id: '8',
    title: 'Sales Manager',
    company: 'EthioGoods Inc.',
    location: 'Adama',
    snippet: 'Dynamic Sales Manager needed to lead our sales team and expand market reach. Proven track record in sales leadership.',
    jobUrl: 'https://example.com/job/8',
    industry: 'Sales',
    jobType: 'Full-time',
    experienceLevel: 'Manager',
    postedDate: '2024-07-26',
  },
  {
    id: '9',
    title: 'Part-time English Tutor',
    company: 'LearnWell Academy',
    location: 'Addis Ababa',
    snippet: 'Part-time opportunity for experienced English tutors to teach students of various levels. Flexible hours.',
    jobUrl: 'https://example.com/job/9',
    industry: 'Education',
    jobType: 'Part-time',
    experienceLevel: 'Mid-level',
    postedDate: '2024-07-23',
  },
  {
    id: '10',
    title: 'Project Manager (Construction)',
    company: 'Mega Builders PLC',
    location: 'Mekelle',
    snippet: 'Experienced Project Manager to oversee large-scale construction projects from inception to completion. PMP certification is a plus.',
    jobUrl: 'https://example.com/job/10',
    industry: 'Engineering',
    jobType: 'Contract',
    experienceLevel: 'Lead',
    postedDate: '2024-07-19',
    logoUrl: 'https://placehold.co/100x100.png',
  },
];

export const EthiopianMajorCities = [
  "Addis Ababa",
  "Adama",
  "Awassa (Hawassa)",
  "Bahir Dar",
  "Dire Dawa",
  "Gondar",
  "Mekelle",
  "Jimma",
  "Dessie",
  "Jijiga"
];
